all:
  hosts:
    localhost:
      ansible_connection: local



      # webserver:
      # ansible_host: 172.20.10.3
      #  ansible_user: ubuntu
      #  ansible_port: 22
          # ansible_shell_type: powershell # in baraye vaghti ke be windows mikhaym ssh bezanim
