---
- name: Test DNS
  command: getent hosts vault.centos.org
  changed_when: false

- name: Fix CentOS 8 repositories
  shell: |
    sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo
    sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"
    
  - name: Check target OS and DNS
    shell: |
      echo "=== OS ==="
      cat /etc/os-release
      echo "=== DNS ==="
      cat /etc/resolv.conf
      echo "=== RESOLVE ==="
      getent hosts mirrorlist.centos.org
    register: debug_info
    changed_when: false

  - name: Show debug info
    debug:
      var: debug_info.stdout
  - name: install nginx 
    package:
      name: "{{packages}}"
      state: latest
  - name: start and enable Nginx Service
    service:
      name: nginx
      state: started
      enabled: yes
  - name: copy nginx config
    template:
      src: site.conf.j2
      dest: /etc/nginx/conf.d/mysitee.conf
    notify: restart nginx service
  - debug:
      var: ansible_default_ipv4.address
  - debug:
      var: ansible_memtotal_mb
  - debug:
      var: ansible_date_time

# tasks file for roles/nginx
